// Generated by CoffeeScript 1.6.1
(function() {
  var autoLink,
    __slice = [].slice;

  autoLink = function() {
    var key, linkAttributes, option, options, pattern, value;
    options = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    linkAttributes = '';
    option = options[0];
    pattern = /(^|\s)((?:https?|ftp):\/\/[\-A-Z0-9+\u0026@#\/%?=~_|!:,.;]*[\-A-Z0-9+\u0026@#\/%=~_|])/gi;
    if (!(options.length > 0)) {
      return this.replace(pattern, "$1<a href='$2'>$2</a>");
    }
    for (key in option) {
      value = option[key];
      if (key !== 'callback') {
        linkAttributes += " " + key + "='" + value + "'";
      }
    }
    return this.replace(pattern, function(match, space, url) {
      var link;
      link = (typeof option.callback === "function" ? option.callback(url) : void 0) || ("<a href='" + url + "'" + linkAttributes + ">" + url + "</a>");
      return "" + space + link;
    });
  };

  String.prototype['autoLink'] = autoLink;

}).call(this);
